name: "Proposal"
description: Suggest a product enhancement idea! We'll review these as part of our ongoing roadmap planning process.
title: "[service] [request]: describe request here"
labels: [Proposed, Triage]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]() and affirm you have read and accept the the [Forward Looking Statement]() and [Salesforce Program Agreement]()
      options:
          - label: I agree to follow this project's Code of Conduct
            required: true
          - label: I have read and accept the [Forward Looking Statement]() and [Salesforce Program Agreement]()
            required: true
