name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:


name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: legal-terms
    attributes:
      label: Legal Terms
      description: By submitting this issue, you affirm you have read and and accept the [Forward Looking Statement]() and [Salesforce Program Agreement]().
      options:
        - label: I have read and accept the [Forward Looking Statement]() and [Salesforce Program Agreement]()
          required: true
  - type: markdown
    attributes:
      value: |
        ### Note\n
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue.
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request. 
        * Only thumbs up reactions will be counted as votes during the Heroku team's review.
- type: textarea
  attributes:
    label: **What service(s) is this request for?** 
    description: This could be dynos, Postgres, Connect, etc
  validations:
    required: true
- type: textarea
  attributes:
    label: **Tell us about what you're trying to solve. What challenges are you facing?** 
    description: What's the impact of not having this impemented? The more information and context you can provide, the better we're able to understand it and work on solutions.
    render: markdown
  validations:
    required: true
