name: "🐞 Bug"
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
  - type: checkboxes
    id: terms
    attributes:
      options:
        - label: I agree to follow this project's [Code of Conduct](https://example.com)
          required: true
  - type: textarea
    attributes:
    label: What service(s) is this request for?
    validations:
      required: true
